# Generated by Django 4.1.2 on 2022-11-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_no',
            field=models.CharField(max_length=32, unique=True, verbose_name='学号'),
        ),
    ]
